# ============================================================
# DATA QUALITY REPORT EXPORT
# ============================================================

def build_quality_report(result, dataset_name, status, ai_advice=None):

    lines = [
        "# Data Quality Assessment Report",
        "",
        f"**Dataset:** {dataset_name}",
        f"**Overall Score:** {result['quality_score']}/100",
        f"**Status:** {status}",
        f"**Rows:** {result['total_rows']}",
        f"**Columns:** {result['total_columns']}",
        f"**Issues Detected:** {result['total_issues']}",
        "",
        "## Quality Dimensions",
        "",
    ]

    for dimension, score in result["quality_dimensions"].items():

        display_score = (
            f"{score}/100"
            if score is not None
            else "Not evaluated"
        )

        lines.append(
            f"- **{dimension}:** {display_score}"
        )

    lines.extend([
        "",
        "## Severity Distribution",
        "",
    ])

    for severity, count in result["severity_counts"].items():
        lines.append(f"- **{severity}:** {count}")

    lines.extend([
        "",
        "## Detected Quality Issues",
        "",
    ])

    if not result["issues"]:
        lines.append("No issues detected.")

    for issue in result["issues"]:

        lines.append(
            f"- **[{issue['severity']}] {issue['category']}** "
            f"({issue['column']}): {issue['message']}"
        )

    lines.extend([
        "",
        "## AI Advisor Analysis",
        "",
    ])

    if ai_advice:
        lines.append(ai_advice)
    else:
        lines.append(
            "AI analysis has not been generated."
        )

    lines.extend([
        "",
        "---",
        "Generated by AI Data Quality Agent.",
        "Deterministic controls + Local LLM interpretation.",
        "",
    ])

    return "\n".join(lines)